# This stage installs our modules
FROM node:12.16 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY ./tcd-app/package.json /usr/src/app/package.json

RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./tcd-app /usr/src/app
CMD ["npm", "start"]